name: Build Rust project with nightly toolchain

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust nightly toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly

    - name: Build Rust project with nightly toolchain
      run: cargo +nightly build --release
